version: '3'
services:
  nodejs:
    image: shopper-backend
    restart: always
    build: .
    ports:
      - 3001:3001
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword